my_site/my_site/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, ),
    path('', include('p_library.urls', ), ),
    # path('__debug__/', include('debug_toolbar.urls', ), ),
]

if settings.DEBUG:
    # import debug_toolbar

    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls', ), ),
    ] + urlpatterns

my_site/p_library/urls.py
from django.urls import path
from p_library import views

app_name = 'p_library'

urlpatterns = [
    path('', views.index, name="home", ),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create', ),
    path('book/create/', views.BookCreate.as_view(), name='book_create', ),
    path('reader/create/', views.ReaderCreate.as_view(), name='reader_create', ),
    path('publisher/create/', views.PublisherCreate.as_view(), name='publisher_create', ),
    path('authors/', views.AuthorsList.as_view(), name='authors', ),
    path('books/', views.BooksList.as_view(), name="books", ),
    path('readers/', views.ReadersList.as_view(), name="readers", ),
    path('publishers/', views.PublishersList.as_view(), name="publishers", ),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='view_author', ),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='view_book', ),
    path('reader/<int:pk>/', views.ReaderDetail.as_view(), name='view_reader', ),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='view_publisher', ),
    path('author/<int:pk>/edit/', views.AuthorUpdate.as_view(), name='author_edit', ),
    path('book/<int:pk>/edit/', views.BookUpdate.as_view(), name='book_edit', ),
    path('reader/<int:pk>/edit/', views.ReaderUpdate.as_view(), name='reader_edit', ),
    path('publisher/<int:pk>/edit/', views.PublisherUpdate.as_view(), name='publisher_edit', ),
    path('book_increment/', views.book_increment, name="book_increment", ),
    path('book_decrement/', views.book_decrement, name="book_decrement", ),
    # path('author/create_many/', views.author_create_many, name='author_create_many', ),
    # path('author_book/create_many/', views.books_authors_create_many, name='author_book_create_many', ),
]

my_site/templates/base.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <title>Библиотека{% block title %}{% endblock %}</title>
        <nav class="nav nav-tabs bg-primary bg-opacity-10">
            <a class="nav-link" href="{% url 'p_library:home' %}" tabindex="-1">Главная</a>
            <a class="nav-link" href="{% url 'p_library:books' %}">Книги</a>
            <a class="nav-link" href="{% url 'p_library:authors' %}">Авторы</a>
            <a class="nav-link" href="{% url 'p_library:publishers' %}">Издательства</a>
            <a class="nav-link" href="{% url 'p_library:readers' %}">Читатели</a>
            <a class="nav-link" href="{% url 'p_library:book_create' %}">&#43; книга</a>   
            <a class="nav-link" href="{% url 'p_library:author_create' %}">&#43; автор</a>                       
            <a class="nav-link" href="{% url 'p_library:publisher_create' %}">&#43; издательство</a>     
            <a class="nav-link" href="{% url 'p_library:reader_create' %}">&#43; читатель</a>              
        </nav>
    </head>
    <body class="text-primary bg-success bg-opacity-10">
        <h3 class="mx-3">{% block welcome %}{% endblock %}</h3>
        {% block main %}
        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>        
    </body>
</html>