my_site/my_site/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls, ),
    path('', include('p_library.urls', ), ),
    # path('__debug__/', include('debug_toolbar.urls', ), ),
]

if settings.DEBUG:
    # import debug_toolbar

    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls', ), ),
    ] + urlpatterns

my_site/p_library/urls.py
from django.urls import path
from p_library import views

app_name = 'p_library'

urlpatterns = [
    path('', views.index, name="home", ),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create', ),
    path('book/create/', views.BookCreate.as_view(), name='book_create', ),
    path('reader/create/', views.ReaderCreate.as_view(), name='reader_create', ),
    path('publisher/create/', views.PublisherCreate.as_view(), name='publisher_create', ),
    path('authors/', views.AuthorsList.as_view(), name='authors', ),
    path('books/', views.BooksList.as_view(), name="books", ),
    path('readers/', views.ReadersList.as_view(), name="readers", ),
    path('publishers/', views.PublishersList.as_view(), name="publishers", ),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='view_author', ),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='view_book', ),
    path('reader/<int:pk>/', views.ReaderDetail.as_view(), name='view_reader', ),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='view_publisher', ),
    path('author/<int:pk>/edit/', views.AuthorUpdate.as_view(), name='author_edit', ),
    path('book/<int:pk>/edit/', views.BookUpdate.as_view(), name='book_edit', ),
    path('reader/<int:pk>/edit/', views.ReaderUpdate.as_view(), name='reader_edit', ),
    path('publisher/<int:pk>/edit/', views.PublisherUpdate.as_view(), name='publisher_edit', ),
    path('book_increment/', views.book_increment, name="book_increment", ),
    path('book_decrement/', views.book_decrement, name="book_decrement", ),
    # path('author/create_many/', views.author_create_many, name='author_create_many', ),
    # path('author_book/create_many/', views.books_authors_create_many, name='author_book_create_many', ),
]

my_site/p_library/models.py
from string import Template
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from django.utils.translation import gettext as _


class Author(models.Model):
    class Meta:
        verbose_name = _("объект Автор")
        verbose_name_plural = _("Авторы")

    full_name = models.TextField(
        verbose_name=_("Имя автора"),
        default=_("Неизвестен"),
    )
    birth_year = models.PositiveSmallIntegerField(
        verbose_name=_("Год рождения"),
        blank=True,
        null=True,
    )
    country = models.CharField(
        verbose_name=_("Страна"),
        max_length=2,        
        blank=True,
        null=True,        
    )

    def get_absolute_url(self):
        return reverse_lazy('p_library:view_author', kwargs={'pk': self.pk})

    def __str__(self):
        return Template('$name').substitute(name=self.full_name)


class Book(models.Model):
    class Meta:
        verbose_name = _("объект Книга")
        verbose_name_plural = _("Книги")

    ISBN = models.CharField(
        max_length=13,
        verbose_name=_("Международный стандартный "
                       "книжный номер"),
    )
    title = models.TextField(
        verbose_name=_("Название"),
    )
    description = models.TextField(
        verbose_name=_("Аннотация"),
        blank=True,
    )
    year_release = models.PositiveSmallIntegerField(
        verbose_name=_("Год выхода в свет"),
        blank=True,
    )
    copy_count = models.PositiveSmallIntegerField(
        verbose_name=_("Число копий"),
        default=1,
    )
    price = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        verbose_name=_("Цена"),
    )
    author = models.ForeignKey(
        "p_library.Author",
        verbose_name=_("Автор"),        
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="book_author",
    )
    publisher = models.ForeignKey(
        "p_library.Publisher",
        verbose_name=_("Издательство"),
        on_delete=models.CASCADE,
        null=True,
        blank=True,        
        related_name="books",
    )
    year_publishing = models.PositiveIntegerField(
        verbose_name=_("Год издания"),
        blank=True,
    )
    readers = models.ManyToManyField(
        "p_library.Reader",
        through='BookReader',
        symmetrical=False,
        verbose_name=_("Сейчас читают"),
        related_name="reading_books",
        blank=True,
    )

    def get_absolute_url(self):
        return reverse_lazy('p_library:view_book', kwargs={'pk': self.pk})

    def __str__(self):
        return Template('$title').substitute(title=self.title)


class Publisher(models.Model):
    class Meta:
        verbose_name = _("Издательство")
        verbose_name_plural = _("Издательства")

    name = models.TextField(
        verbose_name=_("Издательство"),
        default=_("Неизвестно"),
    )
    country = models.CharField(
        max_length=2,
        verbose_name=_("Страна"),
    )
    city = models.CharField(
        max_length=25, default="unknown",
        verbose_name=_("Город"),
    )

    def get_absolute_url(self):
        return reverse_lazy('p_library:view_publisher', kwargs={'pk': self.pk})    

    def __str__(self):
        return Template('$name').substitute(name=self.name)


class Reader(models.Model):
    class Meta:
        verbose_name = _("Читатель")
        verbose_name_plural = _("Читатели")

    name = models.TextField(
        verbose_name=_("Читатель"),
    )
    address = models.TextField(
        verbose_name=_("Адрес"),
        default=_("Планета Земля"),
    )

    def get_absolute_url(self):
        return reverse_lazy('p_library:view_reader', kwargs={'pk': self.pk})

    def __str__(self):
        return Template('$name').substitute(name=self.name)


class BookReader(models.Model):
    book = models.ForeignKey(
        Book,
        verbose_name=_("Сейчас читает:"),
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="book_reading_reader",
    )
    reader = models.ForeignKey(
        Reader,
        verbose_name=_("Эту книгу сейчас читают:"),
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="reader_reading_book",
    )
    borrow_date = models.DateField(
        verbose_name=_("Дата"),
        null=True,
        blank=True,
        auto_now=True,
    )

    def save(self, *args, **kwargs):
        if BookReader.objects.filter(book_id=self.book_id).count() < self.book.copy_count:
            super(BookReader, self).save(*args, **kwargs)  # Call the "real" save() method
        else:
            #raise ValidationError("К сожалению, все копии книги на руках. Зайдите попозже :)")
            return # Do nothing

my_site/p_library/forms.py
# from dataclasses import field
# from email.policy import default
# from socket import fromshare
from django import forms
from django.utils.translation import gettext as _
from p_library.models import Author, Book, Publisher, Reader
from django.core.exceptions import ValidationError


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'    

    full_name = forms.CharField(
        max_length=150,            
        label=_("Полное имя автора"),        
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    birth_year = forms.IntegerField(
        label=_("Год рождения"),
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control", })        
    ) 
    country = forms.CharField(
        max_length=2,            
        label=_("Страна"),        
        widget=forms.TextInput(attrs={"class": "form-control"})
    )       


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

    ISBN = forms.CharField(
        max_length=13,
        label="ISBN",
        widget=forms.TextInput(attrs={"class": "form-control", })
    )
    title = forms.CharField(
        max_length=150,            
        label=_("Название"),
        widget=forms.TextInput(attrs={"class": "form-control", })            
    )
    description = forms.CharField(
        label=_("Аннотация"),
        required=False,
        widget=forms.Textarea(attrs={
            "class": "form-control",
            "rows": 5, })              
    )
    year_release = forms.IntegerField(
        label=_("Год выхода в свет"),
        widget=forms.TextInput(attrs={"class": "form-control", })        
    )
    copy_count = forms.IntegerField(
        label=_("Количество копий"),        
        required=False,
        min_value=1,
        initial=1,        
        widget=forms.NumberInput(attrs={"class": "form-control", })
    )
    price = forms.DecimalField(
        max_digits=12,
        decimal_places=2,
        label=_("Цена"),
        widget=forms.TextInput(attrs={"class": "form-control", })          
    )
    author = forms.ModelChoiceField(
        queryset=Author.objects.all(),
        label=_("Автор"),
        empty_label=_("Неизвестен"),
        initial=_("Неизвестен"),        
        required=False, 
        widget=forms.Select(attrs={"class": "form-control", })    
    )        
    publisher = forms.ModelChoiceField(
        queryset=Publisher.objects.all(),        
        label=_("Издательство"),
        empty_label=_("Неизвестно"), 
        initial=_("Неизвестно"),
        required=False,        
        widget=forms.Select(attrs={"class": "form-control", }) 
    )
    year_publishing = forms.IntegerField(
        label=_("Год издания"),
        widget=forms.TextInput(attrs={"class": "form-control", })         
    )
    readers = forms.ModelMultipleChoiceField(
        queryset=Reader.objects.all(),     
        label=_("Сейчаc читают"),
        required=False, 
        widget=forms.CheckboxSelectMultiple()
    )

    def clean_readers(self):
        readers = self.cleaned_data['readers']
        copy_count = self.cleaned_data['copy_count']
        if len(readers) > copy_count:
            raise forms.ValidationError(f'Количество копий ограничено ({copy_count})')
        return readers


class ReaderForm(forms.ModelForm):
    class Meta:
        model = Reader
        fields = '__all__'   

    name = forms.CharField(
        max_length=150,            
        label=_("Полное имя читателя"),        
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    address = forms.CharField(
        max_length=150,            
        label=_("Адрес"),        
        widget=forms.TextInput(attrs={"class": "form-control"})
    )       


class PublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = '__all__'  
            
    name = forms.CharField(
        max_length=150,            
        label=_("Название издательства"),        
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    country = forms.CharField(
        max_length=2,            
        label=_("Страна"),        
        widget=forms.TextInput(attrs={"class": "form-control"})
    )       
    city = forms.CharField(
        max_length=150,            
        label=_("Город"),        
        widget=forms.TextInput(attrs={"class": "form-control"})       
    )
  

my_site/p_library/views.py
from p_library.models import Author, Book, Reader, Publisher, BookReader
from p_library.forms import AuthorForm, BookForm, ReaderForm, PublisherForm
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse_lazy


def index(request):
    welcome_dict = {
        "welcome_phrase": f"<h5 class='mx-3'>Добро пожаловать в нашу библиотеку!<br>В нашей библиотеке на текущий момент:</h5><h6 class='mx-3'>представлено изданий - {Book.objects.count()}<br>записано читателей - {Reader.objects.count()}</h6><div class='mx-3'>Для навигации по разделам сайта воспользуйтесь<br>меню в верхней части страницы.<br>Желаем приятно и с пользой провести время!</div>",
    }
    return render(request, 'p_library/index.html', context=welcome_dict, )


def copy_count_change(request, action, path_='/books/'):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect(path_)
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect(path_)
            if action == '+':
                book.copy_count += 1
            elif action == '-':
                if book.copy_count == 1:
                    book.copy_count = 1
                elif book.copy_count == len(book.readers.all()):
                    ...
                else:
                    book.copy_count -= 1
            book.save()
        return redirect(path_)
    else:
        return redirect(path_)


def book_increment(request):
    return copy_count_change(request, '+')


def book_decrement(request):
    return copy_count_change(request, '-')


class AuthorCreate(CreateView):
    model = Author
    form_class = AuthorForm
    extra_context = {'info': 'автора'}
    template_name = 'p_library/form_edit.html'


class BookCreate(CreateView):
    model = Book
    form_class = BookForm
    extra_context = {'info': 'книги'}    
    template_name = 'p_library/form_edit.html'


class ReaderCreate(CreateView):
    model = Reader
    form_class = ReaderForm
    extra_context = {'info': 'читателя'}    
    template_name = 'p_library/form_edit.html'


class PublisherCreate(CreateView):
    model = Publisher
    form_class = PublisherForm
    extra_context = {'info': 'издательства'}    
    template_name = 'p_library/form_edit.html'    


class AuthorsList(ListView):
    model = Author
    template_name = 'p_library/authors_list.html'
    context_object_name = 'authors'
    extra_context = {'title': 'Авторы'}

    def get_queryset(self):
        return Author.objects.prefetch_related('book_author', 'book_author__publisher')    


class BooksList(ListView):
    model = Book
    template_name = 'p_library/books_list.html'
    context_object_name = 'books'
    extra_context = {'title': 'Книги'}

    def get_queryset(self):
        return Book.objects.select_related('author', 'publisher').prefetch_related('book_reading_reader')


class PublishersList(ListView):
    model = Publisher
    template_name = 'p_library/publishers_list.html'
    context_object_name = 'publishers'
    extra_context = {'title': 'Издательства'}

    def get_queryset(self):
        return Publisher.objects.prefetch_related('books__author')  


class ReadersList(ListView):
    model = Reader
    template_name = 'p_library/readers_list.html'
    context_object_name = 'readers'
    extra_context = {'title': 'Читатели'}


class AuthorDetail(DetailView):
    model = Author

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Book.objects.filter(author=context['author'])
        return context


class BookDetail(DetailView):
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['readers'] = BookReader.objects.filter(book=context['book'])
        return context


class ReaderDetail(DetailView):
    model = Reader

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = BookReader.objects.filter(reader=context['reader'])
        return context


class PublisherDetail(DetailView):
    model = Publisher

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Book.objects.filter(publisher=context['publisher'])
        return context


class AuthorUpdate(UpdateView):
    model = Author
    form_class = AuthorForm
    extra_context = {'info': 'автора'}    
    success_url = reverse_lazy('p_library:authors')
    template_name = 'p_library/form_edit.html'


class BookUpdate(UpdateView):
    model = Book
    form_class = BookForm
    extra_context = {'info': 'книги'}    
    success_url = reverse_lazy('p_library:books')
    template_name = 'p_library/form_edit.html'
    

class ReaderUpdate(UpdateView):
    model = Reader
    form_class = ReaderForm
    extra_context = {'info': 'читателя'}    
    success_url = reverse_lazy('p_library:readers')
    template_name = 'p_library/form_edit.html'


class PublisherUpdate(UpdateView):
    model = Publisher
    form_class = PublisherForm
    extra_context = {'info': 'издательства'}    
    success_url = reverse_lazy('p_library:publishers')
    template_name = 'p_library/form_edit.html'     

my_site/p_library/templates/p_library/author_detail.html
{% extends 'base.html' %}

{% block title %}

({{ object.full_name }})

{% endblock %}

{% block main %}

<h5 class="mx-3"><a class="text-decoration-none link-info" href="edit/">{{ object.full_name }}</a> является автором следующих книг из моей библиотеки (всего - {{ books|length }}):</h5>
<ul class="mx-3 list-group list-group-numbered">  
{% for book in books %}      
    <li class="list-group-item">
        <a class="text-decoration-none" href="{{ book.get_absolute_url }}">&#171;{{ book.title }}&#187; (год издания - {{ book.year_publishing }})</a>
    </li>
{% endfor %}
</ul>

{% endblock %}

my_site/p_library/templates/p_library/authors_list.html
{% extends 'base.html' %}

{% block title %}
    ({{ title }})
{% endblock %}

{% block main %}

<h5 class="mx-3">В библиотеке представлены книги следующих авторов:</h5>
<ul class="list-group list-group-numbered">  
{% for author in authors %}      
    <li class="list-group-item list-group-item-action">
        <a class="fw-bold text-decoration-none" href="{{ author.get_absolute_url }}">{{ author.full_name }}</a>
        <ul>
        {% for book in author.book_author.all %}        
            <li class="list-group-item-action">
                <a class="text-decoration-none" href="{{ book.get_absolute_url }}">&#171;{{ book.title }}&#187; 
                {% if book.publisher %}
                    <a class="text-decoration-none link-info" href="{{ book.publisher.get_absolute_url }}">(изд. &#171;{{ book.publisher }}&#187;). </a>
                {% else %}
                    (издательство неизвестно). 
                {% endif %}
                </a>            
                Год издания - {{ book.year_publishing }}
            </li>  
        {% endfor %}                           
        </ul>
    </li>
{% endfor %}
{% load p_library_get_objects %}
{% get_books_None_author as books %}
{% if books %}
    <li class="list-group-item list-group-item-action">
        <a class="fw-bold text-decoration-none" href="">Автор неизвестен</a>
        <ul>
        {% for book in books %}
            <li class="list-group-item-action">
                <a class="text-decoration-none" href="{{ book.get_absolute_url }}">&#171;{{ book.title }}&#187; </a>
                {% if book.publisher %}
                    <a class="text-decoration-none link-info" href="{{ book.publisher.get_absolute_url }}">(изд. &#171;{{ book.publisher }}&#187;). </a>
                {% else %}
                    (издательство неизвестно). 
                {% endif %}                    
                Год издания - {{ book.year_publishing }}
            </li>     
        {% endfor %}
        </ul>
    </li>                
{% endif %}
</ul>

{% endblock %}

my_site/p_library/templates/p_library/book_detail.html
{% extends 'base.html' %}

{% block title %}
({{ object.title }})
{% endblock %}

{% block main %}

<h5 class="mx-3">Книга <a class="text-decoration-none link-info" href="edit/">&#171;{{ object.title }}&#187;</a> {% if object.author %} автора {{ object.author }}{% else %} неизвестного автора{% endif %}. Всего копий в наличии: {{ object.copy_count }}</h5>
<h5 class="mx-3">Сейчас эту книгу читают:</h5>
{% if not readers %}
    <p class="mx-3">Пока никто</p>
{% else %}
    <ul class="mx-3 list-group list-group-numbered">  
    {% for reader in readers %}      
        <li class="list-group-item">
            <a class="text-decoration-none" href="{{ reader.reader.get_absolute_url }}">{{ reader.reader.name }}</a>
        </li>
    {% endfor %}
    </ul>
{% endif %}

{% endblock %}

my_site/p_library/templates/p_library/books_list.html
{% extends 'base.html' %}

{% block title %}
({{ title }})
{% endblock %}

{% block main %}

<h5 class="text-center">В библиотеке представлены следующие книги:</h5>
<table class="table table-bordered table-sm align-middle table-hover">
    <thead class="table-dark text-center align-middle">
        <tr>
            <th>Номер</th>
            <th>ISBN</th>
            <th>Название</th>  
            <th>Выход в свет</th>              
            <th>Описание</th>        
            <th>Автор</th>
            <th>Страна</th>
            <th>Издательство</th>
            <th>Год издания</th>
            <th>Сейчас читают</th>
            <th>Есть в наличии</th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
        <tr>
            <td class="text-center">{{ forloop.counter }}</td>
            <td>{{ book.ISBN }}</td>
            <td>
                <a class="text-decoration-none" href="{{ book.get_absolute_url }}">
                    {{ book.title }}
                </a>
            </td>
            <td class="text-center">{{ book.year_release }}</td>        
            <td>{{ book.description }}</td>        
            <td>
                {% if book.author.full_name %}
                    {% autoescape off %}                
                        <a class="text-decoration-none" href="{{ book.author.get_absolute_url }}">
                            {{ book.author.full_name }}
                        </a>                            
                    {% endautoescape %}                              
                {% else %}
                    Неизвестен
                {% endif %}
            </td>
            <td class="text-center">
                {% if book.author.country %}
                    {{ book.author.country }}
                {% else %}
                    ??
                {% endif %}                    
            </td>
            <td>
                {% if book.publisher.name %}
                    {% autoescape off %}
                        <a class="text-decoration-none" href="{{ book.publisher.get_absolute_url }}">
                            {{ book.publisher.name }}
                    {% endautoescape %}                            
                {% else %}
                    Неизвестно
                {% endif %}
                </a>
            </td>
            <td class="text-center">{{ book.year_publishing }}</td>
            <td class="text-center">{{ book.book_reading_reader.all|length }}</td>
            <td class="align-middle">
                <div class="d-flex flex-row">
                    <form action="{% url 'p_library:book_decrement' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ book.id }}"/>
                        <input type="submit" value="&#8722;" style="background-color: rgb(212, 253, 239);"/>
                    </form>
                    <div class="flex-grow-1 text-center fw-bold pt-1" style="padding: 2px;">
                        {{ book.copy_count }}
                    </div>
                    <form action="{% url 'p_library:book_increment' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ book.id }}"/>
                        <input type="submit" value="&#43;" style="background-color: rgb(255, 222, 210);"/>
                    </form>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

my_site/p_library/templates/p_library/form_edit.html
{% extends 'base.html' %}

{% block title %}
	(Форма создания и редактирования {{ info }})
{% endblock %}

{% block main %}

<div class="d-flex flex-row">
	<div class="col-md-3">
	</div>
	<div class="col-md-6 mx-3">
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<div class="d-grid">
				<button type="submit" class="btn btn-primary">Сохранить</button>
			</div>
		</form>	
	</div>
	<div class="col-md-3">
	</div>
</div>

{% endblock %}

my_site/p_library/templates/p_library/index.html
{% extends 'base.html' %}

{% block welcome %}

{% autoescape off %}
{{ welcome_phrase }}
{% endautoescape %}


{% comment %}
<div class="container">
<!--<h5>-->
    <div class="row">
        <div class="col-3"></div>
        <div><!-- class="col-6 center-text text-dark" class="d-flex flex-md-column">-->
            <h4 class="center-text text-dark">Добро пожаловать в мою библиотеку!</h4>
            <h5>В библиотеке собраны книги различных авторов, всего -  </h5>
            <h5>На данный момент в библиотеку записано читателей -  </h5>
            <h5>Для навигации по разделам сайта воспользуйтесь меню в верхней части страницы.</h5>
            <h5>Желаю приятно и с пользой провести время!</h5>
        </div>
        <div class="col-3"></div>
    </div>
<!--</h5>-->
</div>
{% endcomment %}
{% endblock %}

my_site/p_library/templates/p_library/publisher_detail.html
{% extends 'base.html' %}

{% block title %}
({{ object.name }})
{% endblock %}

{% block main %}

<h5 class="mx-3">В издательстве <a class="text-decoration-none link-info" href="edit/">&#171;{{ object.name }}&#187;</a> вышли в свет следующие книги из моей библиотеки (всего - {{ books|length }}):</h5>
<ul class="mx-3 list-group list-group-numbered">  
    {% for book in books %}      
        <li class="list-group-item">  <!-- list-group-item-info"> -->
            <a class="text-decoration-none" href="{{ book.get_absolute_url }}">&#171;{{ book.title }}&#187; (год издания - {{ book.year_publishing }})</a>
        </li>
    {% endfor %}
</ul>

{% endblock %}

my_site/p_library/templates/p_library/publishers_list.html
{% extends 'base.html' %}

{% block title %}
    ({{ title }})
{% endblock %}

{% block main %}

<h5 class="mx-3">В библиотеке представлены книги следующих издательств:</h5>
<ul class="list-group list-group-numbered">
{% for publisher in publishers %}      
    <li class="list-group-item list-group-item-action">
        <a class="fw-bold text-decoration-none"
           href="{{ publisher.get_absolute_url }}">&#171;{{ publisher.name }}&#187; ({{ publisher.city }}, {{ publisher.country }})</a>
        <ul>
        {% for book in publisher.books.all %}                  
            <li class="list-group-item-action">
                <a class="text-decoration-none" href="{{ book.get_absolute_url }}">&#171;{{ book.title }}&#187; 
                {% if book.author %}
                    <a class="text-decoration-none link-info" href="{{ book.author.get_absolute_url }}">({{ book.author }}).
                    </a>
                {% else %}
                   (автор неизвестен). 
                {% endif %}
                </a>
                Год издания - {{ book.year_publishing }}
            </li>  
        {% endfor %} 
        </ul>
    </li>
{% endfor %}
{% load p_library_get_objects %}
{% get_books_None_publisher as books %}
{% if books %}
    <li class="list-group-item list-group-item-action">
        <a class="fw-bold text-decoration-none" href="">Издательство неизвестно</a>
        <ul>
        {% for book in books %}
            <li class="list-group-item-action">
                <a class="text-decoration-none" href="{{ book.get_absolute_url }}">&#171;{{ book.title }}&#187; 
                {% if book.author %}
                    <a class="text-decoration-none link-info" href="{{ book.author.get_absolute_url }}">({{ book.author }}).
                    </a>
                {% else %}
                    (автор неизвестен). 
                {% endif %} 
                </a>
                Год издания - {{ book.year_publishing }}
            </li>     
        {% endfor %}
        </ul>
    </li>                
{% endif %}
</ul>

{% endblock %}

my_site/p_library/templates/p_library/reader_detail.html
{% extends 'base.html' %}

{% block title %}
({{ object.name }})
{% endblock %}

{% block main %}

<h5 class="mx-3"><a class="text-decoration-none link-info" href="edit/">{{ object.name }}</a> сейчас читает:</h5>
<ul class="mx-3 list-group list-group-numbered">  
{% if not books %}
    <h5 class="mx-3">Пока ничего</h5>
{% else %}
{% for book in books %}
{% if book.book %}
    <li class="list-group-item">
        <a class="text-decoration-none" href="{{ book.book.get_absolute_url }}">&#171;{{ book.book }}&#187; </a>
        {% if book.book.author %}
            <a class="text-decoration-none link-info" href="{{ book.book.author.get_absolute_url }}">({{ book.book.author }})</a>
        {% else %}
            (автор неизвестен)
        {% endif %} - с {{ book.borrow_date }}
    </li>
{% endif %}
{% endfor %}
{% endif %}
</ul>

{% endblock %}

my_site/p_library/templates/p_library/readers_list.html
{% extends 'base.html' %}

{% block title %}
({{ title }})
{% endblock %}

{% block main %}

<h5 class="mx-3">В нашу библиотеку записаны:</h5>
<ul class="list-group list-group-numbered">  
{% for reader in readers %}      
    <li class="list-group-item">
        <a class="text-decoration-none" href="{{ reader.get_absolute_url }}">{{ reader.name }}</a>
    </li>
{% endfor %}
</ul>

{% endblock %}